[package]
name = "spread-maker"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
imgui = "0.12.0"
raylib = "5.5.1"
raylib_imgui_rs = "0.5.0"

[profile.release]
opt-level = 3
